/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class main_NativeKeyBoard */

#ifndef _Included_main_NativeKeyBoard
#define _Included_main_NativeKeyBoard
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     main_NativeKeyBoard
	 * Method:    getASyncKeyState
	 * Signature: (I)I
	 */
	JNIEXPORT jint JNICALL Java_main_NativeKeyBoard_getASyncKeyState
	(JNIEnv*, jobject, jint);

	/*
	 * Class:     main_NativeKeyBoard
	 * Method:    getKeyState
	 * Signature: (I)I
	 */
	JNIEXPORT jint JNICALL Java_main_NativeKeyBoard_getKeyState
	(JNIEnv*, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
